name: Publish Docker Image

on:
  push:
    tags:
      - 'v*' # 仅当推送标签时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Extract repository name (in lowercase)
      - name: Extract repository name
        id: extract_repo
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=repo_name::$REPO_NAME"

      # Step 5: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo_name }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo_name }}:${{ github.ref_name }}

      # Step 6: Verify the Docker image (optional)
      - name: Verify Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ steps.extract_repo.outputs.repo_name }}:${{ github.ref_name }}
